server:
  port: ${FRONTEND_SERVICE_PORT:8081}

spring:
  application:
    name: frontend-service
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true

baseUrl: ${APP_URL:http://localhost:8080}

jwt:
  expiration: ${JWT_EXPIRATION:24}

cookie:
  auth-name: ${COOKIE_AUTH_NAME:authToken}