server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: frontend-service
              uri: http://localhost:8081
              predicates:
                - Path=/**
              order: 1000

            - id: auth-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/auth/**

            - id: patient-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/patients/**

            - id: note-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/notes/**

            - id: assessment-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/assessment/**

jwt:
  public-key-path: ${JWT_PUBLIC_KEY_PATH:./secrets/jwt_public.pem}

cookie:
  auth-name: ${COOKIE_AUTH_NAME:authToken}