server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: frontend-service
              uri: lb://frontend-service
              predicates:
                - Path=/**
              order: 1000

            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**

            - id: patient-service
              uri: lb://patient-service
              predicates:
                - Path=/api/patients/**

            - id: note-service
              uri: lb://notes-service
              predicates:
                - Path=/api/notes/**

            - id: assessment-service
              uri: lb://assessment-service
              predicates:
                - Path=/api/assessment/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

jwt:
  public-key-path: ${JWT_PUBLIC_KEY_PATH:./secrets/jwt_public.pem}

cookie:
  auth-name: ${COOKIE_AUTH_NAME:authToken}
