server:
  port: ${ASSESSMENT_SERVICE_PORT:8085}

spring:
  application:
    name: assessment-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

cookie:
  auth-name: ${COOKIE_AUTH_NAME:authToken}
