server:
  port: ${NOTE_SERVICE_PORT:8084}

spring:
  application:
    name: note-service
  data:
    mongodb:
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}
      database: ${MONGODB_DATABASE:diabetes_detection}
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:password}
      authentication-database: ${MONGODB_AUTH:admin}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}